services:
  backend:
    build: ./backend
    ports:
      - '3001:3001'
    environment:
      - PORT=3001
    volumes:
      - ./backend:/usr/src/app
      - /usr/src/app/node_modules
    command: npm run dev

  frontend:
    build:
      context: ./frontend
      target: development
    ports:
      - '5173:5173'
    environment:
      - VITE_API_URL=http://localhost:3001/api/calculate
    volumes:
      - ./frontend:/usr/src/app
      - /usr/src/app/node_modules
    command: npm run dev
    depends_on:
      - backend
