name: Check

on:
  push:
    branches: ['main']

env:
  FORCE_JAVASCRIPT_ACTIONS_TO_NODE24: true

jobs:
  backend-test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v6
      - name: Setup Node.js
        uses: actions/setup-node@v6
        with:
          node-version: '22'
      - name: Install backend dependencies
        run: |
          cd backend
          npm install
      - name: Run backend tests
        run: |
          cd backend
          npm test

  frontend-test:
    needs: backend-test
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v6
      - name: Setup Node.js
        uses: actions/setup-node@v6
        with:
          node-version: '22'
      - name: Install frontend dependencies
        run: |
          cd frontend
          npm install
      - name: Run frontend tests
        run: |
          cd frontend
          npm test
